### ISSUE TITLE
Stops filtering if erroneous values are entered in comboMode

### ISSUE THREAD

**Issue by shawndotey** [john-oc/acute-select#37]
While in comboMode, if you type a value not listed, the drop down list will filter until it reaches a value that does not exist.  Then you can not retrieve the full list, only what the last known good filter was. Also, if you filter down to a known value but don't select it, but instead, blur and focus on another element, it will not reset the filtered list, again it will only show the last known good filtered list (not the whole list). And yes this includes deleting what is in the input box.

**Comment by john-oc** [comment]
This is now fixed.
