### ISSUE TITLE
Select multiple values from ac-options

### ISSUE THREAD

**Issue by gsabboz** [john-oc/acute-select#49]
I'm wondering if it is possible to show for example the first name and the last name inside the the dropdown.

I have tried this :  ac-options="s.firstName + ' ' +s.lastName for s in getAllUsers()"

But it only shows the last name.

**Comment by tahaerden** [comment]
Same issue for me. I tried a couple of other valid syntaxes, but none of them worked. Do you have any solution for displaying multiple fields?
